version: '3.6'
networks:
  kbase-dev:
    name: kbase-dev
services:
  kbase-ui-plugin-organizations:
    build:
      context: .
      dockerfile: Dockerfile
    image: kbase/kbase-ui-plugin-organizations:dev
    container_name: kbase-ui-plugin-organizations
    dns: 8.8.8.8
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
    networks:
      - kbase-dev
    command: /bin/sh -c "while sleep 1000; do :; done"
 