export enum ActionFlag {
    APP = 1,
    APP_START,
    APP_SUCCESS,
    // APP_SUCCESS_IFRAME,
    // APP_SUCCESS_SOLO,
    APP_ERROR,

    SORT_ORGS,
    SORT_ORGS_START,

    FILTER_ORGS,
    FILTER_ORGS_START,

    SEARCH_ORGS,
    SEARCH_ORGS_START,
    SEARCH_ORGS_SUCCESS,
    SEARCH_ORGS_ERROR,

    UPDATE_ORG,
    UPDATE_ORG_START,
    UPDATE_ORG_SUCCESS,
    UPDATE_ORG_ERROR,

    // viewing org
    VIEW_ORG_FETCH,
    VIEW_ORG_FETCH_START,
    VIEW_ORG_FETCH_SUCCESS,
    VIEW_ORG_FETCH_ERROR,
    VIEW_ORG_STOP,

    // Joining and Such
    VIEW_ORG_JOIN_REQUEST,
    VIEW_ORG_JOIN_REQUEST_START,
    VIEW_ORG_JOIN_REQUEST_SUCCESS,
    VIEW_ORG_JOIN_REQUEST_ERROR,

    VIEW_ORG_CANCEL_JOIN_REQUEST,
    VIEW_ORG_CANCEL_JOIN_REQUEST_START,
    VIEW_ORG_CANCEL_JOIN_REQUEST_SUCCESS,
    VIEW_ORG_CANCEL_JOIN_REQUEST_ERROR,

    VIEW_ORG_ACCEPT_JOIN_INVITATION,
    VIEW_ORG_ACCEPT_JOIN_INVITATION_START,
    VIEW_ORG_ACCEPT_JOIN_INVITATION_SUCCESS,
    VIEW_ORG_ACCEPT_JOIN_INVITATION_ERROR,


    VIEW_ORG_REJECT_JOIN_INVITATION,
    VIEW_ORG_REJECT_JOIN_INVITATION_START,
    VIEW_ORG_REJECT_JOIN_INVITATION_SUCCESS,
    VIEW_ORG_REJECT_JOIN_INVITATION_ERROR,

    VIEW_ORG_REMOVE_NARRATIVE,
    VIEW_ORG_REMOVE_NARRATIVE_START,
    VIEW_ORG_REMOVE_NARRATIVE_SUCCESS,
    VIEW_ORG_REMOVE_NARRATIVE_ERROR,

    // add org fields
    ADD_ORG_EDIT,
    ADD_ORG_EDIT_START,
    ADD_ORG_EDIT_FINISH,

    ADD_ORG_UPDATE_NAME,
    ADD_ORG_UPDATE_NAME_SUCCESS,
    ADD_ORG_UPDATE_NAME_ERROR,

    ADD_ORG_UPDATE_GRAVATAR_HASH,
    ADD_ORG_UPDATE_GRAVATAR_HASH_SUCCESS,
    ADD_ORG_UPDATE_GRAVATAR_HASH_ERROR,

    ADD_ORG_UPDATE_ID,
    ADD_ORG_UPDATE_ID_SUCCESS,
    ADD_ORG_UPDATE_ID_ERROR,

    ADD_ORG_UPDATE_DESCRIPTION,
    ADD_ORG_UPDATE_DESCRIPTION_SUCCESS,
    ADD_ORG_UPDATE_DESCRIPTION_ERROR,

    ADD_ORG_EVALUATE,
    ADD_ORG_EVALUATE_OK,
    ADD_ORG_EVALUATE_ERRORS,

    ADD_ORG,
    ADD_ORG_START,
    ADD_ORG_SUCCESS,
    ADD_ORG_ERROR,

    // editing org
    EDIT_ORG_EDIT,
    EDIT_ORG_EDIT_START,
    EDIT_ORG_EDIT_SUCCESS,
    EDIT_ORG_EDIT_ERROR,

    EDIT_ORG_SAVE,
    EDIT_ORG_SAVE_START,
    EDIT_ORG_SAVE_SUCCESS,
    EDIT_ORG_SAVE_ERROR,

    // edit org, field level updates
    EDIT_ORG_UPDATE_NAME,
    EDIT_ORG_UPDATE_NAME_SUCCESS,
    EDIT_ORG_UPDATE_NAME_ERROR,

    EDIT_ORG_UPDATE_GRAVATAR_HASH,
    EDIT_ORG_UPDATE_GRAVATAR_HASH_SUCCESS,
    EDIT_ORG_UPDATE_GRAVATAR_HASH_ERROR,

    EDIT_ORG_UPDATE_DESCRIPTION,
    EDIT_ORG_UPDATE_DESCRIPTION_SUCCESS,
    EDIT_ORG_UPDATE_DESCRIPTION_ERROR,

    EDIT_ORG_EVALUATE,
    EDIT_ORG_EVALUATE_OK,
    EDIT_ORG_EVALUATE_ERRORS,

    // Auth
    AUTH_CHECK,
    AUTH_CHECK_START,
    AUTH_CHECK_ERROR,
    AUTH_AUTHORIZED,
    AUTH_UNAUTHORIZED,
    AUTH_REMOVE_AUTHORIZATION,
    AUTH_ADD_AUTHORIZATION,
    AUTH_ADD_AUTHORIZATION_ERROR,

    ADMIN_MANAGE_REQUESTS,
    ADMIN_MANAGE_REQUESTS_START,
    ADMIN_MANAGE_REQUESTS_SUCCESS,
    ADMIN_MANAGE_REQUESTS_ERROR,

    ADMIN_MANAGE_REQUESTS_ACCEPT_JOIN_REQUEST,
    ADMIN_MANAGE_REQUESTS_ACCEPT_JOIN_REQUEST_START,
    ADMIN_MANAGE_REQUESTS_ACCEPT_JOIN_REQUEST_SUCCESS,
    ADMIN_MANAGE_REQUESTS_ACCEPT_JOIN_REQUEST_ERROR,

    ADMIN_MANAGE_REQUESTS_DENY_JOIN_REQUEST,
    ADMIN_MANAGE_REQUESTS_DENY_JOIN_REQUEST_START,
    ADMIN_MANAGE_REQUESTS_DENY_JOIN_REQUEST_SUCCESS,
    ADMIN_MANAGE_REQUESTS_DENY_JOIN_REQUEST_ERROR,

    ADMIN_MANAGE_REQUESTS_CANCEL_JOIN_INVITATION,
    ADMIN_MANAGE_REQUESTS_CANCEL_JOIN_INVITATION_START,
    ADMIN_MANAGE_REQUESTS_CANCEL_JOIN_INVITATION_SUCCESS,
    ADMIN_MANAGE_REQUESTS_CANCEL_JOIN_INVITATION_ERROR,

    // MEMBERS
    VIEW_MEMBERS_LOAD,
    VIEW_MEMBERS_LOAD_START,
    VIEW_MEMBERS_LOAD_SUCCESS,
    VIEW_MEMBERS_LOAD_ERROR,
    VIEW_MEMBERS_UNLOAD,

    VIEW_MEMBERS_REMOVE_MEMBER,
    VIEW_MEMBERS_REMOVE_MEMBER_START,
    VIEW_MEMBERS_REMOVE_MEMBER_SUCCESS,
    VIEW_MEMBERS_REMOVE_MEMBER_ERROR,

    VIEW_MEMBERS_PROMOTE_TO_ADMIN,
    VIEW_MEMBERS_PROMOTE_TO_ADMIN_START,
    VIEW_MEMBERS_PROMOTE_TO_ADMIN_SUCCESS,
    VIEW_MEMBERS_PROMOTE_TO_ADMIN_ERROR,

    VIEW_MEMBERS_DEMOTE_TO_MEMBER,
    VIEW_MEMBERS_DEMOTE_TO_MEMBER_START,
    VIEW_MEMBERS_DEMOTE_TO_MEMBER_SUCCESS,
    VIEW_MEMBERS_DEMOTE_TO_MEMBER_ERROR,

    // INVITE USER
    INVITE_USER_LOAD,
    INVITE_USER_LOAD_START,
    INVITE_USER_LOAD_READY,
    INVITE_USER_LOAD_ERROR,

    INVITE_USER_SEARCH_USERS,
    INVITE_USER_SEARCH_USERS_START,
    INVITE_USER_SEARCH_USERS_SUCCESS,
    INVITE_USER_SEARCH_USERS_ERROR,

    INVITE_USER_SELECT_USER,
    INVITE_USER_SELECT_USER_START,
    INVITE_USER_SELECT_USER_SUCCESS,
    INVITE_USER_SELECT_USER_ERROR,

    INVITE_USER_SEND_INVITATION,
    INVITE_USER_SEND_INVITATION_START,
    INVITE_USER_SEND_INVITATION_SUCCESS,
    INVITE_USER_SEND_INVITATION_ERROR,

    // Manage Membership
    MANAGE_MEMBERSHIP_LOAD,
    MANAGE_MEMBERSHIP_LOAD_START,
    MANAGE_MEMBERSHIP_LOAD_SUCCESS,
    MANAGE_MEMBERSHIP_LOAD_ERROR,

    // Narrative add requests
    REQUEST_ADD_NARRATIVE_LOAD,
    REQUEST_ADD_NARRATIVE_LOAD_START,
    REQUEST_ADD_NARRATIVE_LOAD_SUCCESS,
    REQUEST_ADD_NARRATIVE_LOAD_ERROR,

    REQUEST_ADD_NARRATIVE_SEND,
    REQUEST_ADD_NARRATIVE_SEND_START,
    REQUEST_ADD_NARRATIVE_SEND_SUCCESS,
    REQUEST_ADD_NARRATIVE_SEND_ERROR,

    REQUEST_ADD_NARRATIVE_SELECT_NARRATIVE,
    REQUEST_ADD_NARRATIVE_SELECT_NARRATIVE_START,
    REQUEST_ADD_NARRATIVE_SELECT_NARRATIVE_SUCCESS,
    REQUEST_ADD_NARRATIVE_SELECT_NARRATIVE_ERROR

}
